win32, msvc: fix missing linking against Bcrypt.lib
Fixes this link error:

dict.obj : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function xmlInitRandom

Commit 4a657062ed8d89d5ab48b7d5ec4770170e323ddc (dict: Get random seed
from system PRNG, 2023-12-24) updated cmake, but not nmake, correct
this.