error: Fix direct invocation of SAX error handlers
Revert part of commit f317aa1f to make it safe to call the default SAX
error handlers directly. This has been deprecated for a long time but
even xmllint still uses these handlers.

Should fix #713.